// This file was autogenerated by lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../src/js_uncompiled/bar/bar.js', ['automatedclosure.bar.Bar'], ['goog.dom']);
goog.addDependency('../../../src/js_uncompiled/foo/foo.js', ['automatedclosure.foo.Foo'], ['goog.dom']);
goog.addDependency('../../../src/js_uncompiled/init.js', ['automatedclosure.init'], ['automatedclosure.bar.Bar', 'automatedclosure.foo.Foo', 'goog.dom']);
